// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqXpoMHRbibWkiLVKsGGg3RVpjI2f2U4o',
    appId: '1:871111009322:android:df709b6f92ec3173678f53',
    messagingSenderId: '871111009322',
    projectId: 'tareas-creciendo-con-flutter',
    databaseURL: 'https://tareas-creciendo-con-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'tareas-creciendo-con-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwMbakC6n-LHaTE4gMzgRTySUX2tIUXec',
    appId: '1:871111009322:ios:6a296f24581682b0678f53',
    messagingSenderId: '871111009322',
    projectId: 'tareas-creciendo-con-flutter',
    databaseURL: 'https://tareas-creciendo-con-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'tareas-creciendo-con-flutter.appspot.com',
    androidClientId: '871111009322-6b8jnb78bor9ftrdjmlu9in6ve23bkht.apps.googleusercontent.com',
    iosClientId: '871111009322-3ilt9nde0oo3gr7qlfrq5if34vu7gnpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.creciendoConFlutter',
  );

}